defaults:
  - _self_
  - metaworld_task: drawer_close

suite: metaworld

name: 'metaworld'

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
hidden_dim: 1024
obs_shape: [3, 84, 84]
action_shape: [4,]


# train settings
num_train_frames: 510000
num_train_frames_bc: 110000
num_seed_frames: 12000

# eval
eval_every_frames: 10000
num_eval_episodes: 50

# snapshot
save_snapshot: true

task_make_fn:
  _target_: suite.metaworld.make
  name: ${suite.metaworld_task.task_name}
  frame_stack: ${suite.frame_stack}
  action_repeat: ${suite.action_repeat}
  seed: ${seed}